- hosts: all
  become: true
  vars:
    container_count: 1
    default_container_name: docker
    default_container_image: centos
    default_container_command: sleep 1d
    
  tasks:
   - name: Install required system packages on RHEL
     become: true
     dnf:
       name:
         - python3-pip
         - python3
         - python3-setuptools
       state: latest

   - name: Add Docker GPG Key
     become: true
     rpm_key:
       key: https://download.docker.com/linux/centos/gpg
       state: present

   - name: Add Docker Repository
     become: true
     yum_repository:
       name: docker-ce
       description: Docker CE Stable
       baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
       gpgkey: https://download.docker.com/linux/centos/gpg
       enabled: true

   - name: Install Docker on Red Hat-based system
     become: true
     dnf:
       name: docker-ce
       state: latest
       
   - name: Install Docker Module for Python
     become: true
     pip:
       name: docker
       
   - name: Start Docker service
     service:
       name: docker
       state: started
        
   - name: Create Docker Network
     command: "docker network create --subnet=172.168.10.0/30 apache_network"
     ignore_errors: true 

   - name: Pull Apache Docker Image
     become: true
     docker_image:
       name: httpd:latest
       source: pull

   - name: Create and Run Apache Docker Container
     docker_container:
       name: apache_container
       image: httpd:latest
       state: started
       restart_policy: always
       detach: true
       ports:
         - "80:80"
       networks:
         - name: apache_network

   - name: Ensure Docker is enabled on boot
     systemd:
       name: docker
       enabled: yes
       

